# The meltan.ca hosted zone, managed in the meltan-ca-global workspace.
# Hardcoded rather than looked up by name: a route53:ListHostedZones lookup
# can't be IAM-scoped to a single zone, and this ID is already public
# information (it's not a secret), same as environments/stage/main.tf.
locals {
  hosted_zone_id = "Z038765422KUTVSCFJIK2"
}

module "bucket" {
  source = "../../modules/static-site-bucket"

  bucket_name = "meltan.ca"
  mode        = "oai"
  oai_iam_arn = module.cdn.oai_iam_arn

  tags = {
    company = "personal"
  }
}

# Predates this repo, requested by hand in 2022. Import target — see the
# terraform import commands in the PR description.
resource "aws_acm_certificate" "this" {
  provider                  = aws.us_east_1
  domain_name               = "meltan.ca"
  subject_alternative_names = ["blog.meltan.ca", "www.meltan.ca"]
  validation_method         = "DNS"

  options {
    certificate_transparency_logging_preference = "ENABLED"
  }

  tags = {
    company = "personal"
  }

  lifecycle {
    create_before_destroy = true
  }
}

module "cdn" {
  source = "../../modules/cdn"

  origin_domain_name  = module.bucket.bucket_regional_domain_name
  function_name       = "append-index-html"
  aliases             = ["meltan.ca", "www.meltan.ca", "blog.meltan.ca"]
  acm_certificate_arn = aws_acm_certificate.this.arn
  comment             = "meltan.ca"
  default_root_object = "index.html"

  # The pre-existing OAI's console-autogenerated comment, kept as-is on
  # import rather than overwritten with var.comment ("meltan.ca").
  oai_comment = "access-identity-www.meltan.ca.s3.us-west-2.amazonaws.com"

  tags = {
    company     = "personal"
    application = "blog"
  }
}

resource "aws_route53_record" "apex" {
  zone_id = local.hosted_zone_id
  name    = "meltan.ca"
  type    = "A"

  alias {
    name                   = module.cdn.distribution_domain_name
    zone_id                = module.cdn.distribution_hosted_zone_id
    evaluate_target_health = false
  }
}

resource "aws_route53_record" "www" {
  zone_id = local.hosted_zone_id
  name    = "www.meltan.ca"
  type    = "A"

  alias {
    name                   = module.cdn.distribution_domain_name
    zone_id                = module.cdn.distribution_hosted_zone_id
    evaluate_target_health = false
  }
}

resource "aws_route53_record" "blog" {
  zone_id = local.hosted_zone_id
  name    = "blog.meltan.ca"
  type    = "A"

  alias {
    name                   = module.cdn.distribution_domain_name
    zone_id                = module.cdn.distribution_hosted_zone_id
    evaluate_target_health = false
  }
}
